services:
  - type: web
    name: stories-post-backend
    env: node
    plan: free
    buildCommand: |
      echo "Installing dependencies..."
      npm install
      echo "Building TypeScript..."
      npm run build
      echo "Build completed. Checking dist directory:"
      ls -la dist/
    startCommand: |
      echo "Starting application with npm run render..."
      npm run render
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false 